### PR TITLE
Fixed one migration problem and  null level handling in getLevel() & getPoints(),  causing some error

### PR DESCRIPTION
**Pull request by joydeep-bhowmik**
### 1st Issue
When there is no experience record yet and `getPoints()` is executed, it returns the following error message:
```
App\Models\User::getPoints(): Return value must be of type int, null returned.
```
This issue was addressed by modifying two functions as follows:
```php
//src/Concerns/GiveExperience.php
public function getLevel(): int
{
    return $this->experience->status->level ?? 0;
}

public function getPoints(): int
{
    return $this->experience->experience_points ?? 0;
}
```

### 2nd Issue
During migration, the following SQL error was encountered:
```SQL
SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'ended_at' (Connection: mysql, SQL: 
create table `streak_histories` (`id` bigint unsigned not null auto_increment primary key, `user_id` bigint unsigned not 
null, `activity_id` bigint unsigned not null, `count` int not null default '1', `started_at` timestamp not null, `ended_at` 
timestamp not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 
'utf8mb4_unicode_ci')
```
This issue was resolved by adding a nullable constraint to the `ended_at` column in the migration script:
```php
//database/migrations/create_streak_histories_table.php.stub
Schema::create('streak_histories', function (Blueprint $table) {
    $table->id();
    $table->foreignId('user_id')->constrained('users')->cascadeOnDelete();
    $table->foreignId('activity_id')->constrained('streak_activities');
    $table->integer('count')->default(1);
    $table->timestamp('started_at');
    $table->timestamp('ended_at')->nullable(); // Nullable constraint added
    $table->timestamps();
});
```

## Type of Change
- Bug fix 

## Related Issues
- Issue  [#57](https://github.com/cjmellor/level-up/issues/57)

---

### CODE REVIEW

**Comment by cjmellor** [comment]
Thanks for the PR @joydeep-bhowmik 

Could you write a test for point 1, just to make sure it is doing what it is supposed to do?

And the Linter is failing on GA, so can you make sure `pint` is ran on the code?

Thanks.

**Comment by joydeep-bhowmik** [comment]
> Thanks for the PR @joydeep-bhowmik
> 
> Could you write a test for point 1, just to make sure it is doing what it is supposed to do?
> 
> And the Linter is failing on GA, so can you make sure `pint` is ran on the code?
> 
> Thanks.

I will add it as soon as possible ... too much work load this week :(

**Comment by joydeep-bhowmik** [comment]
Sorry for being late . I have updated the codes

**Comment by joydeep-bhowmik** [comment]
unable solve this error  `* [new branch]      main       -> origin/main
error: Your local changes to the following files would be overwritten by checkout:
	src/Concerns/GiveExperience.php
Please commit your changes or stash them before you switch branches.`

**Comment by cjmellor** [comment]
Yeah don't worry about it, I dunno what is up with it

**Review by cjmellor — APPROVED** [review]

**Comment by cjmellor** [comment]
Thanks for the work on this @joydeep-bhowmik. Appreciate it!

**Pull request merged**
